# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wind_direction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wind_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='localisation',
            field=models.CharField(max_length=100),
        ),
    ]
